AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - db/*
    - bin/*
    - spec/**/*
    - app/**/*/*.jbuilder
    - app/**/*/*.rabl
Rails:
  Enabled: true
Rails/HasManyOrHasOneDependent:
  Enabled: false               
Rails/InverseOf:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/Date:
  Enabled: false
Style/MutableConstant:         
  Enabled: false               
Style/DateTime:
  Enabled: false
# Metrics/AbcSize:             
#   Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:          
  Enabled: false
Metrics/LineLength:
  Max: 120
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false               
Style/Documentation:           
  Enabled: false               
Style/ClassAndModuleChildren:  
  Enabled: false
